2024-09-05 20:40:47,990 INFO    StreamThr :725455 [internal.py:wandb_internal():85] W&B internal server running at pid: 725455, started at: 2024-09-05 20:40:47.990091
2024-09-05 20:40:47,991 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: status
2024-09-05 20:40:47,993 INFO    WriterThread:725455 [datastore.py:open_for_write():87] open: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/run-rbtf6ixk.wandb
2024-09-05 20:40:47,993 DEBUG   SenderThread:725455 [sender.py:send():391] send: header
2024-09-05 20:40:47,998 DEBUG   SenderThread:725455 [sender.py:send():391] send: run
2024-09-05 20:40:48,461 INFO    SenderThread:725455 [dir_watcher.py:__init__():211] watching files in: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files
2024-09-05 20:40:48,461 INFO    SenderThread:725455 [sender.py:_start_run_threads():1200] run started: rbtf6ixk with start time 1725536447.989536
2024-09-05 20:40:48,468 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: run_start
2024-09-05 20:40:48,478 DEBUG   HandlerThread:725455 [system_info.py:__init__():26] System info init
2024-09-05 20:40:48,478 DEBUG   HandlerThread:725455 [system_info.py:__init__():41] System info init done
2024-09-05 20:40:48,478 INFO    HandlerThread:725455 [system_monitor.py:start():194] Starting system monitor
2024-09-05 20:40:48,478 INFO    SystemMonitor:725455 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-09-05 20:40:48,478 INFO    HandlerThread:725455 [system_monitor.py:probe():214] Collecting system info
2024-09-05 20:40:48,478 INFO    SystemMonitor:725455 [interfaces.py:start():188] Started cpu monitoring
2024-09-05 20:40:48,479 INFO    SystemMonitor:725455 [interfaces.py:start():188] Started disk monitoring
2024-09-05 20:40:48,479 INFO    SystemMonitor:725455 [interfaces.py:start():188] Started gpu monitoring
2024-09-05 20:40:48,480 INFO    SystemMonitor:725455 [interfaces.py:start():188] Started memory monitoring
2024-09-05 20:40:48,480 INFO    SystemMonitor:725455 [interfaces.py:start():188] Started network monitoring
2024-09-05 20:40:48,492 DEBUG   HandlerThread:725455 [system_info.py:probe():152] Probing system
2024-09-05 20:40:48,493 DEBUG   HandlerThread:725455 [system_info.py:_probe_git():137] Probing git
2024-09-05 20:40:48,497 DEBUG   HandlerThread:725455 [system_info.py:_probe_git():145] Probing git done
2024-09-05 20:40:48,497 DEBUG   HandlerThread:725455 [system_info.py:probe():200] Probing system done
2024-09-05 20:40:48,497 DEBUG   HandlerThread:725455 [system_monitor.py:probe():223] {'os': 'Linux-6.8.0-40-generic-x86_64-with-glibc2.35', 'python': '3.11.0', 'heartbeatAt': '2024-09-05T11:40:48.492540', 'startedAt': '2024-09-05T11:40:47.915704', 'docker': None, 'cuda': None, 'args': ('--n_rollout_threads', '32', '--algorithm_name', 'mast', '--hidden_size', '128', '--map_name', '3m', '--use_wandb'), 'state': 'running', 'program': '/home/hyunwoo/바탕화면/multi-agent/onpolicy/train_smac.py', 'codePathLocal': 'train_smac.py', 'codePath': 'onpolicy/train_smac.py', 'git': {'remote': 'https://github.com/singforai/multi-agent.git', 'commit': 'da9de1eb5cd9698b5c8a1a581c28052b3c38f8cf'}, 'email': 'singfor7012@gmail.com', 'root': '/home/hyunwoo/바탕화면/multi-agent', 'host': 'uos-desktop', 'username': 'hyunwoo', 'executable': '/home/hyunwoo/miniconda3/envs/smac/bin/python', 'cpu_count': 12, 'cpu_count_logical': 24, 'cpu_freq': {'current': 3209.983708333333, 'min': 2200.0, 'max': 3700.0}, 'cpu_freq_per_core': [{'current': 3612.192, 'min': 2200.0, 'max': 3700.0}, {'current': 2200.0, 'min': 2200.0, 'max': 3700.0}, {'current': 3598.8, 'min': 2200.0, 'max': 3700.0}, {'current': 3615.767, 'min': 2200.0, 'max': 3700.0}, {'current': 2200.0, 'min': 2200.0, 'max': 3700.0}, {'current': 2200.0, 'min': 2200.0, 'max': 3700.0}, {'current': 2200.0, 'min': 2200.0, 'max': 3700.0}, {'current': 4516.532, 'min': 2200.0, 'max': 3700.0}, {'current': 3632.831, 'min': 2200.0, 'max': 3700.0}, {'current': 2200.0, 'min': 2200.0, 'max': 3700.0}, {'current': 2200.0, 'min': 2200.0, 'max': 3700.0}, {'current': 2200.0, 'min': 2200.0, 'max': 3700.0}, {'current': 2200.0, 'min': 2200.0, 'max': 3700.0}, {'current': 3601.114, 'min': 2200.0, 'max': 3700.0}, {'current': 3612.065, 'min': 2200.0, 'max': 3700.0}, {'current': 2200.0, 'min': 2200.0, 'max': 3700.0}, {'current': 4107.465, 'min': 2200.0, 'max': 3700.0}, {'current': 4516.368, 'min': 2200.0, 'max': 3700.0}, {'current': 2200.0, 'min': 2200.0, 'max': 3700.0}, {'current': 4536.605, 'min': 2200.0, 'max': 3700.0}, {'current': 4519.194, 'min': 2200.0, 'max': 3700.0}, {'current': 2200.0, 'min': 2200.0, 'max': 3700.0}, {'current': 3616.876, 'min': 2200.0, 'max': 3700.0}, {'current': 2200.0, 'min': 2200.0, 'max': 3700.0}], 'disk': {'/': {'total': 233.17998886108398, 'used': 135.02246856689453}}, 'gpu': 'NVIDIA GeForce RTX 3080', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3080', 'memory_total': 10737418240}, {'name': 'NVIDIA GeForce RTX 3080', 'memory_total': 10737418240}], 'memory': {'total': 62.71548843383789}}
2024-09-05 20:40:48,497 INFO    HandlerThread:725455 [system_monitor.py:probe():224] Finished collecting system info
2024-09-05 20:40:48,497 INFO    HandlerThread:725455 [system_monitor.py:probe():227] Publishing system info
2024-09-05 20:40:48,497 DEBUG   HandlerThread:725455 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-09-05 20:40:49,462 INFO    Thread-12 :725455 [dir_watcher.py:_on_file_created():271] file/dir created: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files/conda-environment.yaml
2024-09-05 20:40:49,765 DEBUG   HandlerThread:725455 [system_info.py:_save_conda():224] Saving conda packages done
2024-09-05 20:40:49,766 INFO    HandlerThread:725455 [system_monitor.py:probe():229] Finished publishing system info
2024-09-05 20:40:49,771 DEBUG   SenderThread:725455 [sender.py:send():391] send: files
2024-09-05 20:40:49,771 INFO    SenderThread:725455 [sender.py:_save_file():1466] saving file wandb-metadata.json with policy now
2024-09-05 20:40:49,807 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: python_packages
2024-09-05 20:40:49,807 DEBUG   SenderThread:725455 [sender.py:send_request():418] send_request: python_packages
2024-09-05 20:40:49,807 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: stop_status
2024-09-05 20:40:49,808 DEBUG   SenderThread:725455 [sender.py:send_request():418] send_request: stop_status
2024-09-05 20:40:49,809 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-05 20:40:50,056 DEBUG   SenderThread:725455 [sender.py:send():391] send: telemetry
2024-09-05 20:40:50,462 INFO    Thread-12 :725455 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files/conda-environment.yaml
2024-09-05 20:40:50,462 INFO    Thread-12 :725455 [dir_watcher.py:_on_file_created():271] file/dir created: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files/requirements.txt
2024-09-05 20:40:50,462 INFO    Thread-12 :725455 [dir_watcher.py:_on_file_created():271] file/dir created: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files/output.log
2024-09-05 20:40:50,462 INFO    Thread-12 :725455 [dir_watcher.py:_on_file_created():271] file/dir created: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files/wandb-metadata.json
2024-09-05 20:40:50,659 INFO    wandb-upload_0:725455 [upload_job.py:push():130] Uploaded file /tmp/tmpxazwcu_mwandb/81fgsi7a-wandb-metadata.json
2024-09-05 20:40:52,463 INFO    Thread-12 :725455 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files/output.log
2024-09-05 20:40:53,183 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:40:58,813 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:40:59,809 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-05 20:41:03,815 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:41:04,807 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: stop_status
2024-09-05 20:41:04,807 DEBUG   SenderThread:725455 [sender.py:send_request():418] send_request: stop_status
2024-09-05 20:41:09,062 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:41:09,808 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-05 20:41:12,748 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: partial_history
2024-09-05 20:41:12,749 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: partial_history
2024-09-05 20:41:12,749 DEBUG   SenderThread:725455 [sender.py:send():391] send: telemetry
2024-09-05 20:41:12,749 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: partial_history
2024-09-05 20:41:12,749 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: partial_history
2024-09-05 20:41:12,749 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: partial_history
2024-09-05 20:41:12,749 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: partial_history
2024-09-05 20:41:12,749 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: partial_history
2024-09-05 20:41:12,749 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: partial_history
2024-09-05 20:41:14,749 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:41:15,474 INFO    Thread-12 :725455 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files/output.log
2024-09-05 20:41:19,762 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:41:19,807 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: stop_status
2024-09-05 20:41:19,808 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-05 20:41:20,002 DEBUG   SenderThread:725455 [sender.py:send_request():418] send_request: stop_status
2024-09-05 20:41:20,267 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: partial_history
2024-09-05 20:41:20,476 INFO    Thread-12 :725455 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files/config.yaml
2024-09-05 20:41:20,477 INFO    Thread-12 :725455 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files/output.log
2024-09-05 20:41:22,354 DEBUG   SenderThread:725455 [sender.py:send():391] send: exit
2024-09-05 20:41:22,354 INFO    SenderThread:725455 [sender.py:send_exit():598] handling exit code: 255
2024-09-05 20:41:22,355 INFO    SenderThread:725455 [sender.py:send_exit():600] handling runtime: 33
2024-09-05 20:41:22,356 INFO    SenderThread:725455 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-09-05 20:41:22,356 INFO    SenderThread:725455 [sender.py:send_exit():606] send defer
2024-09-05 20:41:22,356 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:41:22,356 INFO    HandlerThread:725455 [handler.py:handle_request_defer():184] handle defer: 0
2024-09-05 20:41:22,356 DEBUG   SenderThread:725455 [sender.py:send_request():418] send_request: defer
2024-09-05 20:41:22,356 INFO    SenderThread:725455 [sender.py:send_request_defer():622] handle sender defer: 0
2024-09-05 20:41:22,356 INFO    SenderThread:725455 [sender.py:transition_state():626] send defer: 1
2024-09-05 20:41:22,356 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:41:22,356 INFO    HandlerThread:725455 [handler.py:handle_request_defer():184] handle defer: 1
2024-09-05 20:41:22,356 DEBUG   SenderThread:725455 [sender.py:send_request():418] send_request: defer
2024-09-05 20:41:22,356 INFO    SenderThread:725455 [sender.py:send_request_defer():622] handle sender defer: 1
2024-09-05 20:41:22,356 INFO    SenderThread:725455 [sender.py:transition_state():626] send defer: 2
2024-09-05 20:41:22,356 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:41:22,357 INFO    HandlerThread:725455 [handler.py:handle_request_defer():184] handle defer: 2
2024-09-05 20:41:22,357 INFO    HandlerThread:725455 [system_monitor.py:finish():203] Stopping system monitor
2024-09-05 20:41:22,357 DEBUG   SystemMonitor:725455 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-09-05 20:41:22,357 DEBUG   SystemMonitor:725455 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-09-05 20:41:22,357 DEBUG   SystemMonitor:725455 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-09-05 20:41:22,358 INFO    HandlerThread:725455 [interfaces.py:finish():200] Joined cpu monitor
2024-09-05 20:41:22,358 INFO    HandlerThread:725455 [interfaces.py:finish():200] Joined disk monitor
2024-09-05 20:41:22,462 INFO    HandlerThread:725455 [interfaces.py:finish():200] Joined gpu monitor
2024-09-05 20:41:22,462 INFO    HandlerThread:725455 [interfaces.py:finish():200] Joined memory monitor
2024-09-05 20:41:22,462 INFO    HandlerThread:725455 [interfaces.py:finish():200] Joined network monitor
2024-09-05 20:41:22,462 DEBUG   SenderThread:725455 [sender.py:send_request():418] send_request: defer
2024-09-05 20:41:22,462 INFO    SenderThread:725455 [sender.py:send_request_defer():622] handle sender defer: 2
2024-09-05 20:41:22,462 INFO    SenderThread:725455 [sender.py:transition_state():626] send defer: 3
2024-09-05 20:41:22,462 DEBUG   SenderThread:725455 [sender.py:send():391] send: stats
2024-09-05 20:41:22,462 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:41:22,463 INFO    HandlerThread:725455 [handler.py:handle_request_defer():184] handle defer: 3
2024-09-05 20:41:22,464 DEBUG   SenderThread:725455 [sender.py:send():391] send: history
2024-09-05 20:41:22,464 DEBUG   SenderThread:725455 [sender.py:send_request():418] send_request: summary_record
2024-09-05 20:41:22,464 INFO    SenderThread:725455 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-09-05 20:41:22,464 DEBUG   SenderThread:725455 [sender.py:send_request():418] send_request: defer
2024-09-05 20:41:22,464 INFO    SenderThread:725455 [sender.py:send_request_defer():622] handle sender defer: 3
2024-09-05 20:41:22,464 INFO    SenderThread:725455 [sender.py:transition_state():626] send defer: 4
2024-09-05 20:41:22,464 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:41:22,464 INFO    HandlerThread:725455 [handler.py:handle_request_defer():184] handle defer: 4
2024-09-05 20:41:22,464 DEBUG   SenderThread:725455 [sender.py:send_request():418] send_request: defer
2024-09-05 20:41:22,464 INFO    SenderThread:725455 [sender.py:send_request_defer():622] handle sender defer: 4
2024-09-05 20:41:22,464 INFO    SenderThread:725455 [sender.py:transition_state():626] send defer: 5
2024-09-05 20:41:22,464 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:41:22,464 INFO    HandlerThread:725455 [handler.py:handle_request_defer():184] handle defer: 5
2024-09-05 20:41:22,465 DEBUG   SenderThread:725455 [sender.py:send():391] send: summary
2024-09-05 20:41:22,467 INFO    SenderThread:725455 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-09-05 20:41:22,467 DEBUG   SenderThread:725455 [sender.py:send_request():418] send_request: defer
2024-09-05 20:41:22,467 INFO    SenderThread:725455 [sender.py:send_request_defer():622] handle sender defer: 5
2024-09-05 20:41:22,467 INFO    SenderThread:725455 [sender.py:transition_state():626] send defer: 6
2024-09-05 20:41:22,467 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:41:22,467 INFO    HandlerThread:725455 [handler.py:handle_request_defer():184] handle defer: 6
2024-09-05 20:41:22,467 DEBUG   SenderThread:725455 [sender.py:send_request():418] send_request: defer
2024-09-05 20:41:22,467 INFO    SenderThread:725455 [sender.py:send_request_defer():622] handle sender defer: 6
2024-09-05 20:41:22,467 INFO    SenderThread:725455 [sender.py:transition_state():626] send defer: 7
2024-09-05 20:41:22,468 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:41:22,468 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:41:22,468 INFO    HandlerThread:725455 [handler.py:handle_request_defer():184] handle defer: 7
2024-09-05 20:41:22,468 DEBUG   SenderThread:725455 [sender.py:send_request():418] send_request: defer
2024-09-05 20:41:22,468 INFO    SenderThread:725455 [sender.py:send_request_defer():622] handle sender defer: 7
2024-09-05 20:41:22,477 INFO    Thread-12 :725455 [dir_watcher.py:_on_file_created():271] file/dir created: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files/wandb-summary.json
2024-09-05 20:41:23,354 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-05 20:41:23,477 INFO    Thread-12 :725455 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files/output.log
2024-09-05 20:41:24,477 INFO    Thread-12 :725455 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files/output.log
2024-09-05 20:41:24,711 INFO    SenderThread:725455 [sender.py:transition_state():626] send defer: 8
2024-09-05 20:41:24,711 DEBUG   SenderThread:725455 [sender.py:send_request():418] send_request: poll_exit
2024-09-05 20:41:24,711 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:41:24,712 INFO    HandlerThread:725455 [handler.py:handle_request_defer():184] handle defer: 8
2024-09-05 20:41:24,712 DEBUG   SenderThread:725455 [sender.py:send_request():418] send_request: defer
2024-09-05 20:41:24,712 INFO    SenderThread:725455 [sender.py:send_request_defer():622] handle sender defer: 8
2024-09-05 20:41:24,712 INFO    SenderThread:725455 [job_builder.py:build():443] Attempting to build job artifact
2024-09-05 20:41:24,713 INFO    SenderThread:725455 [job_builder.py:_get_source_type():572] is repo sourced job
2024-09-05 20:41:24,725 INFO    SenderThread:725455 [job_builder.py:build():548] adding wandb-job metadata file
2024-09-05 20:41:24,747 INFO    SenderThread:725455 [sender.py:transition_state():626] send defer: 9
2024-09-05 20:41:24,747 DEBUG   SenderThread:725455 [sender.py:send():391] send: artifact
2024-09-05 20:41:24,747 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:41:24,748 INFO    HandlerThread:725455 [handler.py:handle_request_defer():184] handle defer: 9
2024-09-05 20:41:25,355 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-05 20:41:25,478 INFO    Thread-12 :725455 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files/output.log
2024-09-05 20:41:26,323 INFO    wandb-upload_1:725455 [upload_job.py:push():88] Uploaded file /home/hyunwoo/.local/share/wandb/artifacts/staging/tmparxaw5u7
2024-09-05 20:41:27,001 INFO    wandb-upload_0:725455 [upload_job.py:push():88] Uploaded file /tmp/tmpn6nsm0di/wandb-job.json
2024-09-05 20:41:28,307 INFO    SenderThread:725455 [sender.py:send_artifact():1549] sent artifact job-https___github.com_singforai_multi-agent.git_onpolicy_train_smac.py - {'id': 'QXJ0aWZhY3Q6MTE4MTIzNjkyMg==', 'state': 'PENDING', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjQyMDQ3MDg0OQ==', 'latestArtifact': None}}
2024-09-05 20:41:28,308 DEBUG   SenderThread:725455 [sender.py:send_request():418] send_request: defer
2024-09-05 20:41:28,308 INFO    SenderThread:725455 [sender.py:send_request_defer():622] handle sender defer: 9
2024-09-05 20:41:28,308 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: status_report
2024-09-05 20:41:28,308 INFO    SenderThread:725455 [dir_watcher.py:finish():358] shutting down directory watcher
2024-09-05 20:41:28,479 INFO    SenderThread:725455 [dir_watcher.py:finish():388] scan: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files
2024-09-05 20:41:28,479 INFO    SenderThread:725455 [dir_watcher.py:finish():402] scan save: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files/conda-environment.yaml conda-environment.yaml
2024-09-05 20:41:28,479 INFO    SenderThread:725455 [dir_watcher.py:finish():402] scan save: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files/requirements.txt requirements.txt
2024-09-05 20:41:28,481 INFO    SenderThread:725455 [dir_watcher.py:finish():402] scan save: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files/config.yaml config.yaml
2024-09-05 20:41:28,483 INFO    SenderThread:725455 [dir_watcher.py:finish():402] scan save: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files/wandb-metadata.json wandb-metadata.json
2024-09-05 20:41:28,484 INFO    SenderThread:725455 [dir_watcher.py:finish():402] scan save: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files/output.log output.log
2024-09-05 20:41:28,485 INFO    SenderThread:725455 [dir_watcher.py:finish():402] scan save: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files/wandb-summary.json wandb-summary.json
2024-09-05 20:41:28,486 INFO    SenderThread:725455 [sender.py:transition_state():626] send defer: 10
2024-09-05 20:41:28,486 DEBUG   SenderThread:725455 [sender.py:send_request():418] send_request: poll_exit
2024-09-05 20:41:28,486 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:41:28,487 INFO    HandlerThread:725455 [handler.py:handle_request_defer():184] handle defer: 10
2024-09-05 20:41:28,488 DEBUG   SenderThread:725455 [sender.py:send_request():418] send_request: defer
2024-09-05 20:41:28,488 INFO    SenderThread:725455 [sender.py:send_request_defer():622] handle sender defer: 10
2024-09-05 20:41:28,488 INFO    SenderThread:725455 [file_pusher.py:finish():169] shutting down file pusher
2024-09-05 20:41:28,668 ERROR   wandb-upload_1:725455 [internal_api.py:execute():349] 404 response executing GraphQL.
2024-09-05 20:41:28,668 ERROR   wandb-upload_1:725455 [internal_api.py:execute():350] {"errors":[{"message":"run smac/rbtf6ixk not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-09-05 20:41:28,669 ERROR   Thread-11 (_thread_body):725455 [step_upload.py:_handle_event():144] Failed to upload file: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files/conda-environment.yaml
Traceback (most recent call last):
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 223, in run_and_notify
    self._do_upload(event)
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 243, in _do_upload
    job.run()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 56, in run
    self.push()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 105, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2500, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 317, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
                                ^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-09-05 20:41:28,678 ERROR   wandb-upload_0:725455 [internal_api.py:execute():349] 404 response executing GraphQL.
2024-09-05 20:41:28,678 ERROR   wandb-upload_0:725455 [internal_api.py:execute():350] {"errors":[{"message":"run smac/rbtf6ixk not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-09-05 20:41:28,679 ERROR   Thread-11 (_thread_body):725455 [step_upload.py:_handle_event():144] Failed to upload file: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files/requirements.txt
Traceback (most recent call last):
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 223, in run_and_notify
    self._do_upload(event)
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 243, in _do_upload
    job.run()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 56, in run
    self.push()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 105, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2500, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 317, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
                                ^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-09-05 20:41:28,791 ERROR   wandb-upload_2:725455 [internal_api.py:execute():349] 404 response executing GraphQL.
2024-09-05 20:41:28,791 ERROR   wandb-upload_2:725455 [internal_api.py:execute():350] {"errors":[{"message":"run smac/rbtf6ixk not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-09-05 20:41:28,791 ERROR   Thread-11 (_thread_body):725455 [step_upload.py:_handle_event():144] Failed to upload file: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files/config.yaml
Traceback (most recent call last):
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 223, in run_and_notify
    self._do_upload(event)
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 243, in _do_upload
    job.run()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 56, in run
    self.push()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 105, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2500, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 317, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
                                ^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-09-05 20:41:28,792 ERROR   wandb-upload_3:725455 [internal_api.py:execute():349] 404 response executing GraphQL.
2024-09-05 20:41:28,792 ERROR   wandb-upload_3:725455 [internal_api.py:execute():350] {"errors":[{"message":"run smac/rbtf6ixk not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-09-05 20:41:28,792 ERROR   Thread-11 (_thread_body):725455 [step_upload.py:_handle_event():144] Failed to upload file: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files/output.log
Traceback (most recent call last):
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 223, in run_and_notify
    self._do_upload(event)
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 243, in _do_upload
    job.run()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 56, in run
    self.push()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 105, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2500, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 317, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
                                ^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-09-05 20:41:28,793 ERROR   wandb-upload_4:725455 [internal_api.py:execute():349] 404 response executing GraphQL.
2024-09-05 20:41:28,793 ERROR   wandb-upload_4:725455 [internal_api.py:execute():350] {"errors":[{"message":"run smac/rbtf6ixk not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-09-05 20:41:28,793 ERROR   Thread-11 (_thread_body):725455 [step_upload.py:_handle_event():144] Failed to upload file: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/files/wandb-summary.json
Traceback (most recent call last):
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 223, in run_and_notify
    self._do_upload(event)
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 243, in _do_upload
    job.run()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 56, in run
    self.push()
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 105, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2500, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 317, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
                                ^^^^^^^^^^^^^^^^^
  File "/home/hyunwoo/miniconda3/envs/smac/lib/python3.11/site-packages/wandb/util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-09-05 20:41:28,994 INFO    Thread-11 (_thread_body):725455 [sender.py:transition_state():626] send defer: 11
2024-09-05 20:41:28,994 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:41:28,994 INFO    HandlerThread:725455 [handler.py:handle_request_defer():184] handle defer: 11
2024-09-05 20:41:28,994 DEBUG   SenderThread:725455 [sender.py:send_request():418] send_request: defer
2024-09-05 20:41:28,994 INFO    SenderThread:725455 [sender.py:send_request_defer():622] handle sender defer: 11
2024-09-05 20:41:28,994 INFO    SenderThread:725455 [file_pusher.py:join():175] waiting for file pusher
2024-09-05 20:41:28,995 INFO    SenderThread:725455 [sender.py:transition_state():626] send defer: 12
2024-09-05 20:41:28,995 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:41:28,995 INFO    HandlerThread:725455 [handler.py:handle_request_defer():184] handle defer: 12
2024-09-05 20:41:28,995 DEBUG   SenderThread:725455 [sender.py:send_request():418] send_request: defer
2024-09-05 20:41:28,995 INFO    SenderThread:725455 [sender.py:send_request_defer():622] handle sender defer: 12
2024-09-05 20:41:28,995 INFO    SenderThread:725455 [file_stream.py:finish():601] file stream finish called
2024-09-05 20:41:29,198 INFO    SenderThread:725455 [file_stream.py:finish():605] file stream finish is done
2024-09-05 20:41:29,198 INFO    SenderThread:725455 [sender.py:transition_state():626] send defer: 13
2024-09-05 20:41:29,198 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:41:29,198 INFO    HandlerThread:725455 [handler.py:handle_request_defer():184] handle defer: 13
2024-09-05 20:41:29,199 DEBUG   SenderThread:725455 [sender.py:send_request():418] send_request: defer
2024-09-05 20:41:29,199 INFO    SenderThread:725455 [sender.py:send_request_defer():622] handle sender defer: 13
2024-09-05 20:41:29,199 INFO    SenderThread:725455 [sender.py:transition_state():626] send defer: 14
2024-09-05 20:41:29,199 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: defer
2024-09-05 20:41:29,199 INFO    HandlerThread:725455 [handler.py:handle_request_defer():184] handle defer: 14
2024-09-05 20:41:29,199 DEBUG   SenderThread:725455 [sender.py:send():391] send: final
2024-09-05 20:41:29,200 DEBUG   SenderThread:725455 [sender.py:send():391] send: footer
2024-09-05 20:41:29,200 DEBUG   SenderThread:725455 [sender.py:send_request():418] send_request: defer
2024-09-05 20:41:29,200 INFO    SenderThread:725455 [sender.py:send_request_defer():622] handle sender defer: 14
2024-09-05 20:41:29,200 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-05 20:41:29,201 DEBUG   SenderThread:725455 [sender.py:send_request():418] send_request: poll_exit
2024-09-05 20:41:29,201 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: server_info
2024-09-05 20:41:29,201 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-05 20:41:29,201 DEBUG   SenderThread:725455 [sender.py:send_request():418] send_request: server_info
2024-09-05 20:41:29,203 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: get_summary
2024-09-05 20:41:29,204 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: sampled_history
2024-09-05 20:41:29,204 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-05 20:41:29,395 DEBUG   SenderThread:725455 [sender.py:send_request():418] send_request: poll_exit
2024-09-05 20:41:29,396 INFO    MainThread:725455 [wandb_run.py:_footer_history_summary_info():4078] rendering history
2024-09-05 20:41:29,396 INFO    MainThread:725455 [wandb_run.py:_footer_history_summary_info():4110] rendering summary
2024-09-05 20:41:29,396 INFO    MainThread:725455 [wandb_run.py:_footer_sync_info():4037] logging synced files
2024-09-05 20:41:29,397 DEBUG   HandlerThread:725455 [handler.py:handle_request():158] handle_request: shutdown
2024-09-05 20:41:29,397 INFO    HandlerThread:725455 [handler.py:finish():884] shutting down handler
2024-09-05 20:41:30,201 INFO    WriterThread:725455 [datastore.py:close():296] close: /home/hyunwoo/바탕화면/multi-agent/results/smac/3m/mast/check/wandb/run-20240905_204047-rbtf6ixk/run-rbtf6ixk.wandb
2024-09-05 20:41:30,396 INFO    SenderThread:725455 [sender.py:finish():1631] shutting down sender
2024-09-05 20:41:30,396 INFO    SenderThread:725455 [file_pusher.py:finish():169] shutting down file pusher
2024-09-05 20:41:30,396 INFO    SenderThread:725455 [file_pusher.py:join():175] waiting for file pusher
